name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow when a branch is pushed to with a pattern
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_SECRET_KEY }}
          port: 22
          script: |
            set -e

            # Prepare the deployment directory
            DEPLOY_DIR=/home/ubuntu/deploy-2gether
            APP_DIR=$DEPLOY_DIR/2gether-watch

            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Clean up previous deployments
            if [ -d "$APP_DIR" ]; then
              rm -rf $APP_DIR
            fi
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_rsa
            
            # Clone the repository and checkout the specific branch
            git clone git@github.com:LunavexSoftware/Lunavex.Applications.git
            cd 2gether-watch/2gether-watch

            docker build -t 2gether-watch:latest .

            docker stop 2gether-watch-container || true
            docker rm 2gether-watch-container || true

            docker run -d -p 5072:8080 --name 2gether-watch-container 2gether-watch:latest
            # Clean up after deployment
            cd $DEPLOY_DIR
            rm -rf $APP_DIR